### ISSUE TITLE
user_i2c_write: Remote I/O error

### ISSUE THREAD

**Issue by escalateizzy** [balena-io-projects/balena-sense#33]
Hi all,

Has anyone has found this problem with sensor reading? 

user_i2c_write: Remote I/O error

It starts to happen randomly after some time with device up; and only solves if I reset device.

![error](https://user-images.githubusercontent.com/52623428/62703843-5d480e80-b9ea-11e9-8b6a-21f9b6d8ca45.png)

Thank you in advance

**Comment by danielgreverose** [comment]
I have encountered this issue as well. Has happened twice in the last few days.

**Comment by chrisys** [comment]
@escalateizzy @danielgreverose is this still happening for you guys? It would be great if you could share what hardware you're using; both what Pi and what sensors.

**Comment by escalateizzy** [comment]
Hi, have just updated with last commit thanks. I will give you some feedback after a few days. Hardware using:
Raspberry Pi Zero WH
Generic BME680 sensor https://es.aliexpress.com/item/32961369966.html?spm=a2g0s.9042311.0.0.274263c0VqKpPP

Also tested in the past with Raspberry Pi 3, same error happened.

**Comment by escalateizzy** [comment]
Unfortunately it happened again with latest commit (after 14 hours running).
![err](https://user-images.githubusercontent.com/52623428/66254578-7403ab00-e778-11e9-99c0-85d488e76eeb.jpg)

**Comment by escalateizzy** [comment]
Hi,
Disconnecting and connecting again without turning the Pi off, solved the issue. So really seems like a hardware problem. Will try to test with another sensor board.
Thanks!

**Comment by chrisys** [comment]
@escalateizzy ahh at least we're starting to narrow it down. I'll close this for now then but feel free to reopen it if you're having the same trouble with a new sensor!
