### ISSUE TITLE
Failed install on RPi3B+ 64

### ISSUE THREAD

**Issue by MadDenker** [balena-io-projects/balena-sense#34]
I was unable to deploy the image on a Raspberry Pi 3B+ ARMv8 64-bit.  I believe the 64bit architecture is the issue.  Some error messages:

![image](https://user-images.githubusercontent.com/16837956/63231830-41fdb000-c1ef-11e9-9254-4c59761809ee.png)

![image](https://user-images.githubusercontent.com/16837956/63231818-1e3a6a00-c1ef-11e9-90cd-35f9a3343108.png)

Can you provide a 64bit version?  Thanks.

**Comment by MadDenker** [comment]
Looks like I might just need to point to different install deb packages.  For instance, I probably need to put telegraf_1.11.4-1_arm64.deb in this file: https://github.com/balena-io-projects/balena-sense/blob/a27b006148f51743c3ad564a09e811561beefb55/telegraf/Dockerfile.template

Any ideas on how best to do this?  Should I create a new branch or version or release?  Maybe a test for architecture before wgetting the package?

**Comment by chrisys** [comment]
@MadDenker take a look at how the download for Grafana works - you can probably use %%BALENA_ARCH%% here and make a case for downloading the 64 bit version. A PR would be welcome once you get it up and running!

**Comment by vschinazi** [comment]
@MadDenker did you ever manage to get this working? I am dying to get this working on a pi 4.

**Comment by chrisys** [comment]
@MadDenker this is resolved in https://github.com/balena-io-projects/balena-sense/pull/40 - thanks for posting.

**Comment by MadDenker** [comment]
Awesome!  Thanks!

**Comment by MadDenker** [comment]
I am still having troubles installing it.  
![image](https://user-images.githubusercontent.com/16837956/71547151-142d3280-296a-11ea-984a-20613d8d4509.png)

The first error I see in the output is - 
 [telegraf]  debconf: delaying package configuration, since apt-utils is not installed
